### ISSUE TITLE
make step does not work

### ISSUE THREAD

**Issue by strider82** [talonsensei/codex-python#1]
Hi,
I am trying to follow the steps, everything went fine until cmake, but make fails as below:

Does anybody have an idea how to get past this?

Thanks!

tp-cph-0220:tmp mgi$ make
Scanning dependencies of target shiny-server
[ 30%] Building CXX object src/CMakeFiles/shiny-server.dir/launcher.cc.o
/Users/mgi/shiny-server/src/launcher.cc:41:7: warning: 'daemon' is deprecated: first deprecated in
      OS X 10.5 [-Wdeprecated-declarations]
      daemon(1, 0);
      ^
/usr/include/stdlib.h:267:6: note: 'daemon' has been explicitly marked deprecated here
int      daemon(int, int) __DARWIN_1050(daemon) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0...
         ^
1 warning generated.
[ 30%] Linking CXX executable ../../bin/shiny-server
[ 30%] Built target shiny-server
[ 30%] Performing install step for 'node'
installing /Users/mgi/shiny-server/ext/node/bin/node
Traceback (most recent call last):
  File "tools/install.py", line 156, in <module>
    run(sys.argv[:])
  File "tools/install.py", line 151, in run
    if cmd == 'install': return files(install)
  File "tools/install.py", line 122, in files
    action(['out/Release/node'], 'bin/node')
  File "tools/install.py", line 79, in install
    def install(paths, dst): map(lambda path: try_copy(path, dst), paths)
  File "tools/install.py", line 79, in <lambda>
    def install(paths, dst): map(lambda path: try_copy(path, dst), paths)
  File "tools/install.py", line 71, in try_copy
    return shutil.copy2(source_path, target_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'out/Release/node'
make[3]: **\* [install] Error 1
make[2]: **\* [external/node/node-prefix/src/node-stamp/node-install] Error 2
make[1]: **\* [external/node/CMakeFiles/node.dir/all] Error 2
make: **\* [all] Error 2
tp-cph-0220:tmp mgi$

**Comment by talonsensei** [comment]
Hi,
Did you make the changes to launcher.cc http://launcher.cc/ that were outlined in the linked gist?

-Mark

**Comment by strider82** [comment]
Hi,
Yes. I did. Cmake didn't produce complaints. I will post the cmake compilation stdout tomorrow.
